@echo off
copy %0  "%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\"
nslookup  www.google.cn  8.8.8.8 > google.txt
for /f  %%l  in (google.txt) do (
	:echo %%l
		set IP=%%l
		)
echo %IP%

:C:
:cd C:\Windows\System32\drivers\etc
echo 127.0.0.1      localhost > hosts
echo %IP%       www.baidu.com  >>  hosts
echo #Google Services START  >>  hosts

echo %IP%       chatenabled.mail.google.com  >>  hosts
echo %IP%       static.googleusercontent.com  >>  hosts
echo %IP%       0.docs.google.com  >>  hosts
echo %IP%       0.drive.google.com  >>  hosts
echo %IP%       1.docs.google.com  >>  hosts
echo %IP%       1.drive.google.com  >>  hosts
echo %IP%       10.docs.google.com  >>  hosts
echo %IP%       10.drive.google.com  >>  hosts
echo %IP%       11.docs.google.com  >>  hosts
echo %IP%       11.drive.google.com  >>  hosts
echo %IP%       12.docs.google.com  >>  hosts
echo %IP%       12.drive.google.com  >>  hosts
echo %IP%       13.docs.google.com  >>  hosts
echo %IP%       13.drive.google.com  >>  hosts
echo %IP%       14.docs.google.com  >>  hosts
echo %IP%       14.drive.google.com  >>  hosts
echo %IP%       15.docs.google.com  >>  hosts
echo %IP%       15.drive.google.com  >>  hosts
echo %IP%       16.docs.google.com  >>  hosts
echo %IP%       16.drive.google.com  >>  hosts
echo %IP%       2.docs.google.com  >>  hosts
echo %IP%       2.drive.google.com  >>  hosts
echo %IP%       3.docs.google.com  >>  hosts
echo %IP%       3.drive.google.com  >>  hosts
echo %IP%       4.docs.google.com  >>  hosts
echo %IP%       4.drive.google.com  >>  hosts
echo %IP%       5.docs.google.com  >>  hosts
echo %IP%       5.drive.google.com  >>  hosts
echo %IP%       6.docs.google.com  >>  hosts
echo %IP%       6.drive.google.com  >>  hosts
echo %IP%       7.docs.google.com  >>  hosts
echo %IP%       7.drive.google.com  >>  hosts
echo %IP%       8.docs.google.com  >>  hosts
echo %IP%       8.drive.google.com  >>  hosts
echo %IP%       9.docs.google.com  >>  hosts
echo %IP%       9.drive.google.com  >>  hosts
echo %IP%       accounts.google.com  >>  hosts
echo %IP%       accounts.l.google.com  >>  hosts
echo %IP%       answers.google.com  >>  hosts
echo %IP%       apis.google.com  >>  hosts
echo %IP%       appengine.google.com  >>  hosts
echo %IP%       apps.google.com  >>  hosts
echo %IP%       appspot.l.google.com  >>  hosts
echo %IP%       bks0.books.google.com  >>  hosts
echo %IP%       bks1.books.google.com  >>  hosts
echo %IP%       bks10.books.google.com  >>  hosts
echo %IP%       bks2.books.google.com  >>  hosts
echo %IP%       bks3.books.google.com  >>  hosts
echo %IP%       bks4.books.google.com  >>  hosts
echo %IP%       bks5.books.google.com  >>  hosts
echo %IP%       bks6.books.google.com  >>  hosts
echo %IP%       bks7.books.google.com  >>  hosts
echo %IP%       bks8.books.google.com  >>  hosts
echo %IP%       bks9.books.google.com  >>  hosts
echo %IP%       blogsearch.google.com  >>  hosts
echo %IP%       books.google.com  >>  hosts
echo %IP%       browserchannel-docs.l.google.com  >>  hosts
echo %IP%       browserchannel-spreadsheets.l.google.com  >>  hosts
echo %IP%       browsersync.google.com  >>  hosts
echo %IP%       browsersync.l.google.com  >>  hosts
echo %IP%       buzz.google.com  >>  hosts
echo %IP%       cache.l.google.com  >>  hosts
echo %IP%       cache.pack.google.com  >>  hosts
echo %IP%       calendar.google.com  >>  hosts
echo %IP%       cbk0.google.com  >>  hosts
echo %IP%       cbk1.google.com  >>  hosts
echo %IP%       cbk2.google.com  >>  hosts
echo %IP%       cbk3.google.com  >>  hosts
echo %IP%       cbks0.google.com  >>  hosts
echo %IP%       cbks1.google.com  >>  hosts
echo %IP%       cbks2.google.com  >>  hosts
echo %IP%       cbks3.google.com  >>  hosts
echo %IP%       chart.apis.google.com  >>  hosts
echo %IP%       chatenabled.mail.google.com  >>  hosts
echo %IP%       checkout.google.com  >>  hosts
echo %IP%       checkout.l.google.com  >>  hosts
echo %IP%       chrome.google.com  >>  hosts
echo %IP%       clients.l.google.com  >>  hosts
echo %IP%       clients1.google.com  >>  hosts
echo %IP%       clients2.google.com  >>  hosts
echo %IP%       clients3.google.com  >>  hosts
echo %IP%       clients4.google.com  >>  hosts
echo %IP%       clients5.google.com  >>  hosts
echo %IP%       clients6.google.com  >>  hosts
echo %IP%       clients7.google.com  >>  hosts
echo %IP%       code.google.com  >>  hosts
echo %IP%       code.l.google.com  >>  hosts
echo %IP%       csi.l.google.com  >>  hosts
echo %IP%       desktop.google.com  >>  hosts
echo %IP%       desktop.l.google.com  >>  hosts
echo %IP%       desktop2.google.com  >>  hosts
echo %IP%       developers.google.com  >>  hosts
echo %IP%       ditu.google.com  >>  hosts
echo %IP%       dl.google.com  >>  hosts
echo %IP%       dl.l.google.com  >>  hosts
echo %IP%       dl-ssl.google.com  >>  hosts
echo %IP%       docs.google.com  >>  hosts
echo %IP%       docs0.google.com  >>  hosts
echo %IP%       docs1.google.com  >>  hosts
echo %IP%       docs2.google.com  >>  hosts
echo %IP%       docs3.google.com  >>  hosts
echo %IP%       docs4.google.com  >>  hosts
echo %IP%       docs5.google.com  >>  hosts
echo %IP%       docs6.google.com  >>  hosts
echo %IP%       docs7.google.com  >>  hosts
echo %IP%       docs8.google.com  >>  hosts
echo %IP%       docs9.google.com  >>  hosts
echo %IP%       drive.google.com  >>  hosts
echo %IP%       earth.google.com  >>  hosts
echo %IP%       encrypted.google.com  >>  hosts
echo %IP%       encrypted-tbn.l.google.com  >>  hosts
echo %IP%       encrypted-tbn0.google.com  >>  hosts
echo %IP%       encrypted-tbn1.google.com  >>  hosts
echo %IP%       encrypted-tbn2.google.com  >>  hosts
echo %IP%       encrypted-tbn3.google.com  >>  hosts
echo %IP%       feedburner.google.com  >>  hosts
echo %IP%       feedproxy.google.com  >>  hosts
echo %IP%       filetransferenabled.mail.google.com  >>  hosts
echo %IP%       finance.google.com  >>  hosts
echo %IP%       fusion.google.com  >>  hosts
echo %IP%       geoauth.google.com  >>  hosts
echo %IP%       gg.google.com  >>  hosts
echo %IP%       ghs.google.com  >>  hosts
echo %IP%       ghs.l.google.com  >>  hosts
echo %IP%       ghs46.google.com  >>  hosts
echo %IP%       ghs46.l.google.com  >>  hosts
echo %IP%       google.com  >>  hosts
echo %IP%       googleapis.l.google.com  >>  hosts
echo %IP%       googleapis-ajax.google.com  >>  hosts
echo %IP%       googleapis-ajax.l.google.com  >>  hosts
echo %IP%       googlecode.l.google.com  >>  hosts
echo %IP%       google-public-dns-a.google.com  >>  hosts
echo %IP%       google-public-dns-b.google.com  >>  hosts
echo %IP%       goto.google.com  >>  hosts
echo %IP%       groups.google.com  >>  hosts
echo %IP%       groups.l.google.com  >>  hosts
echo %IP%       groups-beta.google.com  >>  hosts
echo %IP%       gxc.google.com  >>  hosts
echo %IP%       id.google.com  >>  hosts
echo %IP%       id.l.google.com  >>  hosts
echo %IP%       images.google.com  >>  hosts
echo %IP%       images.l.google.com  >>  hosts
echo %IP%       investor.google.com  >>  hosts
echo %IP%       jmt0.google.com  >>  hosts
echo %IP%       kh.google.com  >>  hosts
echo %IP%       kh.l.google.com  >>  hosts
echo %IP%       khm.google.com  >>  hosts
echo %IP%       khm.l.google.com  >>  hosts
echo %IP%       khm0.google.com  >>  hosts
echo %IP%       khm1.google.com  >>  hosts
echo %IP%       khm2.google.com  >>  hosts
echo %IP%       khm3.google.com  >>  hosts
echo %IP%       khmdb.google.com  >>  hosts
echo %IP%       khms.google.com  >>  hosts
echo %IP%       khms.l.google.com  >>  hosts
echo %IP%       khms0.google.com  >>  hosts
echo %IP%       khms1.google.com  >>  hosts
echo %IP%       khms2.google.com  >>  hosts
echo %IP%       khms3.google.com  >>  hosts
echo %IP%       labs.google.com  >>  hosts
echo %IP%       large-uploads.l.google.com  >>  hosts
echo %IP%       lh2.google.com  >>  hosts
echo %IP%       lh2.l.google.com  >>  hosts
echo %IP%       lh3.google.com  >>  hosts
echo %IP%       lh4.google.com  >>  hosts
echo %IP%       lh5.google.com  >>  hosts
echo %IP%       lh6.google.com  >>  hosts
echo %IP%       linkhelp.clients.google.com  >>  hosts
echo %IP%       local.google.com  >>  hosts
echo %IP%       m.google.com  >>  hosts
echo %IP%       mail.google.com  >>  hosts
echo %IP%       map.google.com  >>  hosts
echo %IP%       maps.google.com  >>  hosts
echo %IP%       maps.l.google.com  >>  hosts
echo %IP%       maps-api-ssl.google.com  >>  hosts
echo %IP%       mars.google.com  >>  hosts
echo %IP%       mobile.l.google.com  >>  hosts
echo %IP%       mobile-gtalk.l.google.com  >>  hosts
echo %IP%       mobilemaps.clients.google.com  >>  hosts
echo %IP%       mt.google.com  >>  hosts
echo %IP%       mt.l.google.com  >>  hosts
echo %IP%       mt0.google.com  >>  hosts
echo %IP%       mt1.google.com  >>  hosts
echo %IP%       mt2.google.com  >>  hosts
echo %IP%       mt3.google.com  >>  hosts
echo %IP%       mtalk.google.com  >>  hosts
echo %IP%       mts.google.com  >>  hosts
echo %IP%       mts.l.google.com  >>  hosts
echo %IP%       mts0.google.com  >>  hosts
echo %IP%       mts1.google.com  >>  hosts
echo %IP%       mts2.google.com  >>  hosts
echo %IP%       mts3.google.com  >>  hosts
echo %IP%       music.google.com  >>  hosts
echo %IP%       music-streaming.l.google.com  >>  hosts
echo %IP%       mw1.google.com  >>  hosts
echo %IP%       mw2.google.com  >>  hosts
echo %IP%       news.google.com  >>  hosts
echo %IP%       news.l.google.com  >>  hosts
echo %IP%       pack.google.com  >>  hosts
echo %IP%       photos.google.com  >>  hosts
echo %IP%       photos-ugc.l.google.com  >>  hosts
echo %IP%       picasa.google.com  >>  hosts
echo %IP%       picasaweb.google.com  >>  hosts
echo %IP%       picasaweb.l.google.com  >>  hosts
echo %IP%       places.google.com  >>  hosts
echo %IP%       play.google.com  >>  hosts
echo %IP%       productforums.google.com  >>  hosts
echo %IP%       profiles.google.com  >>  hosts
echo %IP%       reader.google.com  >>  hosts
echo %IP%       safebrowsing.cache.l.google.com  >>  hosts
echo %IP%       safebrowsing.clients.google.com  >>  hosts
echo %IP%       safebrowsing.google.com  >>  hosts
echo %IP%       safebrowsing-cache.google.com  >>  hosts
echo %IP%       sandbox.google.com  >>  hosts
echo %IP%       sb.google.com  >>  hosts
echo %IP%       sb.l.google.com  >>  hosts
echo %IP%       sb-ssl.google.com  >>  hosts
echo %IP%       sb-ssl.l.google.com  >>  hosts
echo %IP%       scholar.google.com  >>  hosts
echo %IP%       scholar.l.google.com  >>  hosts
echo %IP%       script.google.com  >>  hosts
echo %IP%       services.google.com  >>  hosts
echo %IP%       sites.google.com  >>  hosts
echo %IP%       sketchup.google.com  >>  hosts
echo %IP%       sketchup.l.google.com  >>  hosts
echo %IP%       spreadsheet.google.com  >>  hosts
echo %IP%       spreadsheets.google.com  >>  hosts
echo %IP%       spreadsheets.l.google.com  >>  hosts
echo %IP%       spreadsheets0.google.com  >>  hosts
echo %IP%       spreadsheets1.google.com  >>  hosts
echo %IP%       spreadsheets2.google.com  >>  hosts
echo %IP%       spreadsheets3.google.com  >>  hosts
echo %IP%       spreadsheets4.google.com  >>  hosts
echo %IP%       spreadsheets5.google.com  >>  hosts
echo %IP%       spreadsheets6.google.com  >>  hosts
echo %IP%       spreadsheets7.google.com  >>  hosts
echo %IP%       spreadsheets8.google.com  >>  hosts
echo %IP%       spreadsheets9.google.com  >>  hosts
echo %IP%       spreadsheets-china.l.google.com  >>  hosts
echo %IP%       suggestqueries.google.com  >>  hosts
echo %IP%       suggestqueries.l.google.com  >>  hosts
echo %IP%       support.google.com  >>  hosts
echo %IP%       talk.google.com  >>  hosts
echo %IP%       talkgadget.google.com  >>  hosts
echo %IP%       tbn0.google.com  >>  hosts
echo %IP%       tbn1.google.com  >>  hosts
echo %IP%       tbn2.google.com  >>  hosts
echo %IP%       tbn3.google.com  >>  hosts
echo %IP%       toolbar.google.com  >>  hosts
echo %IP%       toolbarqueries.clients.google.com  >>  hosts
echo %IP%       toolbarqueries.google.com  >>  hosts
echo %IP%       toolbarqueries.l.google.com  >>  hosts
echo %IP%       tools.google.com  >>  hosts
echo %IP%       tools.l.google.com  >>  hosts
echo %IP%       translate.google.com  >>  hosts
echo %IP%       trends.google.com  >>  hosts
echo %IP%       upload.docs.google.com  >>  hosts
echo %IP%       upload.drive.google.com  >>  hosts
echo %IP%       uploads.code.google.com  >>  hosts
echo %IP%       uploadsj.clients.google.com  >>  hosts
echo %IP%       v3.cache1.c.docs.google.com  >>  hosts
echo %IP%       video.google.com  >>  hosts
echo %IP%       video-stats.l.google.com  >>  hosts
echo %IP%       voice.google.com  >>  hosts
echo %IP%       wallet.google.com  >>  hosts
echo %IP%       wifi.google.com  >>  hosts
echo %IP%       wifi.l.google.com  >>  hosts
echo %IP%       wire.l.google.com  >>  hosts
echo %IP%       writely.google.com  >>  hosts
echo %IP%       writely.l.google.com  >>  hosts
echo %IP%       writely-china.l.google.com  >>  hosts
echo %IP%       writely-com.l.google.com  >>  hosts
echo %IP%       www.google.com  >>  hosts
echo %IP%       www.l.google.com  >>  hosts
echo %IP%       www2.l.google.com  >>  hosts
echo %IP%       www3.l.google.com  >>  hosts
echo %IP%       www4.l.google.com  >>  hosts
echo %IP%       ytstatic.l.google.com  >>  hosts
echo %IP%       0-open-opensocial.googleusercontent.com  >>  hosts
echo %IP%       0-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       1-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       1-open-opensocial.googleusercontent.com  >>  hosts
echo %IP%       1-ps.googleusercontent.com  >>  hosts
echo %IP%       2-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       2-open-opensocial.googleusercontent.com  >>  hosts
echo %IP%       2-ps.googleusercontent.com  >>  hosts
echo %IP%       3-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       3-ps.googleusercontent.com  >>  hosts
echo %IP%       3hdrrlnlknhi77nrmsjnjr152ueo3soc-a-calendar-opensocial.googleusercontent.com  >>  hosts
echo %IP%       3-open-opensocial.googleusercontent.com  >>  hosts
echo %IP%       4-ps.googleusercontent.com  >>  hosts
echo %IP%       4fjvqid3r3oq66t548clrdj52df15coc-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       53rd6p0catml6vat6qra84rs0del836d-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       59cbv4l9s05pbaks9v77vc3mengeqors-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       8kubpeu8314p2efdd7jlv09an9i2ljdo-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       adstvca8k2ooaknjjmv89j22n9t676ve-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       blogger.googleusercontent.com  >>  hosts
echo %IP%       bt26mravu2qpe56n8gnmjnpv2inl84bf-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       clients1.googleusercontent.com  >>  hosts
echo %IP%       clients2.googleusercontent.com  >>  hosts
echo %IP%       clients3.googleusercontent.com  >>  hosts
echo %IP%       clients4.googleusercontent.com  >>  hosts
echo %IP%       clients5.googleusercontent.com  >>  hosts
echo %IP%       clients6.googleusercontent.com  >>  hosts
echo %IP%       clients7.googleusercontent.com  >>  hosts
echo %IP%       code-opensocial.googleusercontent.com  >>  hosts
echo %IP%       debh8vg7vd93bco3prdajidmm7dhql3f-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       doc-00-7o-docs.googleusercontent.com  >>  hosts
echo %IP%       doc-08-7o-docs.googleusercontent.com  >>  hosts
echo %IP%       doc-0c-7o-docs.googleusercontent.com  >>  hosts
echo %IP%       doc-0g-7o-docs.googleusercontent.com  >>  hosts
echo %IP%       doc-0s-7o-docs.googleusercontent.com  >>  hosts
echo %IP%       doc-10-7o-docs.googleusercontent.com  >>  hosts
echo %IP%       doc-14-7o-docs.googleusercontent.com  >>  hosts
echo %IP%       feedback.googleusercontent.com  >>  hosts
echo %IP%       googlehosted.l.googleusercontent.com  >>  hosts
echo %IP%       hsco54a20sh11q9jkmb51ad2n3hmkmrg-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       i8brh95qor6r54nkl52hidj2ggcs4jgm-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images1-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images2-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images3-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images4-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images5-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images6-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images7-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images8-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images9-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       images-docs-opensocial.googleusercontent.com  >>  hosts
echo %IP%       k6v18tjr24doa89b55o3na41kn4v73eb-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       lh1.googleusercontent.com  >>  hosts
echo %IP%       lh2.googleusercontent.com  >>  hosts
echo %IP%       lh3.googleusercontent.com  >>  hosts
echo %IP%       lh4.googleusercontent.com  >>  hosts
echo %IP%       lh5.googleusercontent.com  >>  hosts
echo %IP%       lh6.googleusercontent.com  >>  hosts
echo %IP%       mail-attachment.googleusercontent.com  >>  hosts
echo %IP%       music.googleusercontent.com  >>  hosts
echo %IP%       music-onebox.googleusercontent.com  >>  hosts
echo %IP%       oauth.googleusercontent.com  >>  hosts
echo %IP%       ob7f2qc0i50kbjnc81vkhgmb5hsv7a8l-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       ode25pfjgmvpquh3b1oqo31ti5ibg5fr-a-calendar.opensocial.googleusercontent.com  >>  hosts
echo %IP%       qhie5b8u979rnch1q0hqbrmbkn9estf7-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       r70rmsn4s0rhk6cehcbbcbfbs31pu0va-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       rbjhe237k979f79d87gmenp3gejfonu9-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       s1.googleusercontent.com  >>  hosts
echo %IP%       s2.googleusercontent.com  >>  hosts
echo %IP%       s3.googleusercontent.com  >>  hosts
echo %IP%       s4.googleusercontent.com  >>  hosts
echo %IP%       s5.googleusercontent.com  >>  hosts
echo %IP%       s6.googleusercontent.com  >>  hosts
echo %IP%       spreadsheets-opensocial.googleusercontent.com  >>  hosts
echo %IP%       t.doc-0-0-sj.sj.googleusercontent.com  >>  hosts
echo %IP%       themes.googleusercontent.com  >>  hosts
echo %IP%       translate.googleusercontent.com  >>  hosts
echo %IP%       u807isd5egseeabjccgcns005p2miucq-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       upt14k1i2veesusrda9nfotcrbp9d7p5-a-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       webcache.googleusercontent.com  >>  hosts
echo %IP%       www.googleusercontent.com  >>  hosts
echo %IP%       www-calendar-opensocial.googleusercontent.com  >>  hosts
echo %IP%       www-fc-opensocial.googleusercontent.com  >>  hosts
echo %IP%       www-focus-opensocial.googleusercontent.com  >>  hosts
echo %IP%       www-gm-opensocial.googleusercontent.com  >>  hosts
echo %IP%       www-kix-opensocial.googleusercontent.com  >>  hosts
echo %IP%       www-open-opensocial.googleusercontent.com  >>  hosts
echo %IP%       www-opensocial.googleusercontent.com  >>  hosts
echo %IP%       www-opensocial-sandbox.googleusercontent.com  >>  hosts
echo %IP%       www-oz-opensocial.googleusercontent.com  >>  hosts
echo %IP%       csi.gstatic.com  >>  hosts
echo %IP%       g0.gstatic.com  >>  hosts
echo %IP%       g1.gstatic.com  >>  hosts
echo %IP%       g2.gstatic.com  >>  hosts
echo %IP%       g3.gstatic.com  >>  hosts
echo %IP%       maps.gstatic.com  >>  hosts
echo %IP%       mt0.gstatic.com  >>  hosts
echo %IP%       mt1.gstatic.com  >>  hosts
echo %IP%       mt2.gstatic.com  >>  hosts
echo %IP%       mt3.gstatic.com  >>  hosts
echo %IP%       mt4.gstatic.com  >>  hosts
echo %IP%       mt5.gstatic.com  >>  hosts
echo %IP%       mt6.gstatic.com  >>  hosts
echo %IP%       mt7.gstatic.com  >>  hosts
echo %IP%       ssl.gstatic.com  >>  hosts
echo %IP%       t0.gstatic.com  >>  hosts
echo %IP%       t1.gstatic.com  >>  hosts
echo %IP%       t2.gstatic.com  >>  hosts
echo %IP%       t3.gstatic.com  >>  hosts
echo %IP%       www.gstatic.com  >>  hosts
echo %IP%       lh1.ggpht.com  >>  hosts
echo %IP%       lh2.ggpht.com  >>  hosts
echo %IP%       lh3.ggpht.com  >>  hosts
echo %IP%       lh4.ggpht.com  >>  hosts
echo %IP%       lh5.ggpht.com  >>  hosts
echo %IP%       lh6.ggpht.com  >>  hosts
echo %IP%       nt0.ggpht.com  >>  hosts
echo %IP%       nt1.ggpht.com  >>  hosts
echo %IP%       nt2.ggpht.com  >>  hosts
echo %IP%       nt3.ggpht.com  >>  hosts
echo %IP%       nt4.ggpht.com  >>  hosts
echo %IP%       nt5.ggpht.com  >>  hosts
echo %IP%       appspot.com  >>  hosts
echo %IP%       chrometophone.appspot.com  >>  hosts
echo %IP%       evolutionofweb.appspot.com  >>  hosts
echo %IP%       googcloudlabs.appspot.com  >>  hosts
echo %IP%       gv-gadget.appspot.com  >>  hosts
echo %IP%       magnifier.blogspot.com  >>  hosts
echo %IP%       moderator.appspot.com  >>  hosts
echo %IP%       newsfeed-dot-latest-dot-rovio-ad-engine.appspot.com  >>  hosts
echo %IP%       productideas.appspot.com  >>  hosts
echo %IP%       project-slingshot-gp.appspot.com  >>  hosts
echo %IP%       r2303.latest.project-slingshot-hr.appspot.com  >>  hosts
echo %IP%       r3085-dot-latest-dot-project-slingshot-gp.appspot.com  >>  hosts
echo %IP%       r3091-dot-latest-dot-project-slingshot-gp.appspot.com  >>  hosts
echo %IP%       r3101-dot-latest-dot-project-slingshot-gp.appspot.com  >>  hosts
echo %IP%       r3269-dot-latest-dot-project-slingshot-gp.appspot.com  >>  hosts
echo %IP%       r3432-dot-latest-dot-project-slingshot-hr.appspot.com  >>  hosts
echo %IP%       r4681-dot-latest-dot-project-slingshot-hr.appspot.com  >>  hosts
echo %IP%       r7647-dot-latest-dot-project-slingshot-hr.appspot.com  >>  hosts
echo %IP%       wcproxyx.appspot.com  >>  hosts
echo %IP%       www.appspot.com  >>  hosts
echo %IP%       ajax.googleapis.com  >>  hosts
echo %IP%       chart.googleapis.com  >>  hosts
echo %IP%       fonts.googleapis.com  >>  hosts
echo %IP%       maps.googleapis.com  >>  hosts
echo %IP%       mt0.googleapis.com  >>  hosts
echo %IP%       mt1.googleapis.com  >>  hosts
echo %IP%       mt2.googleapis.com  >>  hosts
echo %IP%       mt3.googleapis.com  >>  hosts
echo %IP%       redirector-bigcache.googleapis.com  >>  hosts
echo %IP%       translate.googleapis.com  >>  hosts
echo %IP%       www.googleapis.com  >>  hosts
echo %IP%       autoproxy-gfwlist.googlecode.com  >>  hosts
echo %IP%       chromium.googlecode.com  >>  hosts
echo %IP%       closure-library.googlecode.com  >>  hosts
echo %IP%       earth-api-samples.googlecode.com  >>  hosts
echo %IP%       gmaps-samples-flash.googlecode.com  >>  hosts
echo %IP%       google-code-feed-gadget.googlecode.com  >>  hosts
echo %IP%       blogsearch.google.cn  >>  hosts
echo %IP%       ditu.google.cn  >>  hosts
echo %IP%       gg.google.cn  >>  hosts
echo %IP%       id.google.cn  >>  hosts
echo %IP%       maps.gstatic.cn  >>  hosts
echo %IP%       m.google.cn  >>  hosts
echo %IP%       mt.google.cn  >>  hosts
echo %IP%       mt0.google.cn  >>  hosts
echo %IP%       mt1.google.cn  >>  hosts
echo %IP%       mt2.google.cn  >>  hosts
echo %IP%       mt3.google.cn  >>  hosts
echo %IP%       news.google.cn  >>  hosts
echo %IP%       scholar.google.cn  >>  hosts
echo %IP%       translate.google.cn  >>  hosts
echo %IP%       www.google.cn  >>  hosts
echo %IP%       www.gstatic.cn  >>  hosts
echo %IP%       accounts.google.com.hk  >>  hosts
echo %IP%       blogsearch.google.com.hk  >>  hosts
echo %IP%       books.google.com.hk  >>  hosts
echo %IP%       clients1.google.com.hk  >>  hosts
echo %IP%       desktop.google.com.hk  >>  hosts
echo %IP%       encrypted.google.com.hk  >>  hosts
echo %IP%       groups.google.com.hk  >>  hosts
echo %IP%       gxc.google.com.hk  >>  hosts
echo %IP%       id.google.com.hk  >>  hosts
echo %IP%       images.google.com.hk  >>  hosts
echo %IP%       m.google.com.hk  >>  hosts
echo %IP%       maps.google.com.hk  >>  hosts
echo %IP%       news.google.com.hk  >>  hosts
echo %IP%       picasaweb.google.com.hk  >>  hosts
echo %IP%       plus.url.google.com.hk  >>  hosts
echo %IP%       scholar.google.com.hk  >>  hosts
echo %IP%       toolbar.google.com.hk  >>  hosts
echo %IP%       toolbarqueries.google.com.hk  >>  hosts
echo %IP%       translate.google.com.hk  >>  hosts
echo %IP%       translate.google.com.hk  >>  hosts
echo %IP%       wenda.google.com.hk  >>  hosts
echo %IP%       www.google.com.hk  >>  hosts
echo %IP%       accounts.blogger.com  >>  hosts
echo %IP%       android.googlesource.com  >>  hosts
echo %IP%       auth.keyhole.com  >>  hosts
echo %IP%       chrome.angrybirds.com  >>  hosts
echo %IP%       chromium.org  >>  hosts
echo %IP%       codereview.chromium.org  >>  hosts
echo %IP%       dev.chromium.org  >>  hosts
echo %IP%       developer.android.com  >>  hosts
echo %IP%       developer.chrome.com  >>  hosts
echo %IP%       domains.googlesyndication.com  >>  hosts
echo %IP%       earthengine.googlelabs.com  >>  hosts
echo %IP%       feeds.feedburner.com  >>  hosts
echo %IP%       g.co  >>  hosts
echo %IP%       gmail.com  >>  hosts
echo %IP%       goo.gl  >>  hosts
echo %IP%       listen.googlelabs.com  >>  hosts
echo %IP%       m.gmail.com  >>  hosts
echo %IP%       m.googlemail.com  >>  hosts
echo %IP%       market.android.com  >>  hosts
echo %IP%       ngrams.googlelabs.com  >>  hosts
echo %IP%       panoramio.com  >>  hosts
echo %IP%       smarthosts.googlecode.com  >>  hosts
echo %IP%       ssl.google-analytics.com  >>  hosts
echo %IP%       static.panoramio.com  >>  hosts
echo %IP%       www.blogger.com  >>  hosts
echo %IP%       www.chromium.org  >>  hosts
echo %IP%       www.gmail.com  >>  hosts
echo %IP%       www.googleadservices.com  >>  hosts
echo %IP%       www.google-analytics.com  >>  hosts
echo %IP%       www.googlelabs.com  >>  hosts
echo %IP%       www.googlesource.com  >>  hosts
echo %IP%       www.panoramio.com  >>  hosts
echo %IP%       plus.google.com  >>  hosts
echo %IP%       plus.url.google.com  >>  hosts
echo %IP%       plusone.google.com  >>  hosts
echo #Google Services END  >>  hosts
type hosts
net user administrator /active:yes
copy /Y .\hosts C:\Windows\System32\drivers\etc\hosts

ipconfig /flushdns
pause
